% -------------------------------------------------------------------
%  Generated by MATLAB on 26-Jun-2017 23:27:20
%  MATLAB version: 9.2.0.556344 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('batt_input_10A.mat');

batt_input = saveVarsMat.batt_input; % <2x115281 double> too many elements

clear saveVarsMat;
